FROM locustio/locust:2.15.1

WORKDIR /home/locust

ADD . .

ENV PYTHONUNBUFFERED=1
ENV SIMOD_HTTP_URL=http://simod-http:8000
ENV LOCUST_LOAD_PROFILE=PrepaidTravelCostSingleTask

EXPOSE 8089
EXPOSE 5557

ENTRYPOINT ["bash", "run.sh", "$LOCUST_LOAD_PROFILE"]